#!/usr/bin/env python3
"""
Vector Knowledge Base Search — Advanced search tier for Specialist Sub-Agents.

Uses pre-computed embeddings (generated by kb_embed.py) to find semantically
similar chunks. This finds conceptual matches even when queries use different
words than the KB content.

Returns structured metadata with results (type, category, tags, related entries)
so the specialist can provide richer, more contextual responses.

Requires:
    - An embedding API key (Voyage AI or OpenAI) set as environment variable
    - Pre-computed embeddings in kb_data/embeddings.npz (run kb_embed.py first)
    - Pre-computed chunk metadata in kb_data/chunks.json

Usage:
    python scripts/kb_vector_search.py "your search query" --top 5
    python scripts/kb_vector_search.py "hook framework" --type framework --top 3

Environment variables:
    VOYAGE_API_KEY  — Voyage AI API key (preferred, cheaper)
    OPENAI_API_KEY  — OpenAI API key (fallback)
"""

import argparse
import json
import os
import sys
from pathlib import Path

import numpy as np

# ---------------------------------------------------------------------------
# 1. Embedding providers
# ---------------------------------------------------------------------------

def get_embedding_provider():
    """Detect which embedding API is available."""
    if os.environ.get("VOYAGE_API_KEY"):
        return "voyage"
    elif os.environ.get("OPENAI_API_KEY"):
        return "openai"
    else:
        print(
            "Error: No embedding API key found.\n"
            "Set one of these environment variables:\n"
            "  VOYAGE_API_KEY  (recommended — cheaper and high quality)\n"
            "  OPENAI_API_KEY  (alternative)\n",
            file=sys.stderr,
        )
        sys.exit(1)


def embed_query_voyage(query: str) -> np.ndarray:
    """Get embedding for a query using Voyage AI."""
    import urllib.request

    api_key = os.environ["VOYAGE_API_KEY"]
    data = json.dumps({
        "input": [query],
        "model": "voyage-3-lite",
        "input_type": "query",
    }).encode()

    req = urllib.request.Request(
        "https://api.voyageai.com/v1/embeddings",
        data=data,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
    )

    with urllib.request.urlopen(req) as resp:
        result = json.loads(resp.read())

    return np.array(result["data"][0]["embedding"], dtype=np.float32)


def embed_query_openai(query: str) -> np.ndarray:
    """Get embedding for a query using OpenAI."""
    import urllib.request

    api_key = os.environ["OPENAI_API_KEY"]
    data = json.dumps({
        "input": query,
        "model": "text-embedding-3-small",
    }).encode()

    req = urllib.request.Request(
        "https://api.openai.com/v1/embeddings",
        data=data,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
    )

    with urllib.request.urlopen(req) as resp:
        result = json.loads(resp.read())

    return np.array(result["data"][0]["embedding"], dtype=np.float32)


def embed_query(query: str, provider: str) -> np.ndarray:
    """Route to the correct embedding provider."""
    if provider == "voyage":
        return embed_query_voyage(query)
    elif provider == "openai":
        return embed_query_openai(query)
    raise ValueError(f"Unknown provider: {provider}")


# ---------------------------------------------------------------------------
# 2. Load pre-computed data
# ---------------------------------------------------------------------------

def load_embeddings(kb_data_dir: str) -> tuple[np.ndarray, list[dict]]:
    """Load pre-computed embeddings and chunk metadata."""
    data_path = Path(kb_data_dir)

    embeddings_file = data_path / "embeddings.npz"
    chunks_file = data_path / "chunks.json"

    if not embeddings_file.exists() or not chunks_file.exists():
        print(
            "Error: Pre-computed embeddings not found.\n"
            f"Expected files in: {kb_data_dir}\n"
            "Run kb_embed.py first to generate embeddings.",
            file=sys.stderr,
        )
        sys.exit(1)

    embeddings = np.load(str(embeddings_file))["embeddings"]
    with open(chunks_file, "r", encoding="utf-8") as f:
        chunks = json.load(f)

    if len(embeddings) != len(chunks):
        print("Error: Embedding count doesn't match chunk count.", file=sys.stderr)
        sys.exit(1)

    return embeddings, chunks


# ---------------------------------------------------------------------------
# 3. Search
# ---------------------------------------------------------------------------

def cosine_similarity(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Compute cosine similarity between a query vector and a matrix of vectors."""
    dot_products = b @ a
    norms = np.linalg.norm(b, axis=1) * np.linalg.norm(a)
    return dot_products / np.maximum(norms, 1e-10)


def search(query: str, embeddings: np.ndarray, chunks: list[dict],
           provider: str, top_n: int = 5, type_filter: str = None) -> list[dict]:
    """Embed the query and find the most similar chunks.

    Optionally filter by content type before searching.
    """
    # Apply type filter if specified
    if type_filter:
        indices = [i for i, c in enumerate(chunks)
                   if c.get("type", "").lower() == type_filter.lower()]
        if indices:
            filtered_embeddings = embeddings[indices]
            filtered_chunks = [chunks[i] for i in indices]
        else:
            # Fall back to all if filter matches nothing
            filtered_embeddings = embeddings
            filtered_chunks = chunks
    else:
        filtered_embeddings = embeddings
        filtered_chunks = chunks

    query_embedding = embed_query(query, provider)
    similarities = cosine_similarity(query_embedding, filtered_embeddings)

    # Get top N indices
    top_indices = np.argsort(similarities)[::-1][:top_n]

    results = []
    for idx in top_indices:
        score = float(similarities[idx])
        if score <= 0:
            break
        chunk = filtered_chunks[idx]
        results.append({
            "title": chunk["title"],
            "source": chunk["source"],
            "score": round(score, 4),
            "content": chunk["content"],
            "entry_title": chunk.get("entry_title", ""),
            "type": chunk.get("type", ""),
            "category": chunk.get("category", ""),
            "tags": chunk.get("tags", []),
            "related": chunk.get("related", []),
            "confidence": chunk.get("confidence", ""),
        })

    return results


# ---------------------------------------------------------------------------
# 4. Output
# ---------------------------------------------------------------------------

def format_results(results: list[dict], query: str) -> str:
    """Format search results for Claude to read, including metadata."""
    if not results:
        return f"No results found for: {query}"

    lines = [f"Search results for: {query}", f"Found {len(results)} relevant chunks:", ""]

    for i, r in enumerate(results, 1):
        lines.append(f"--- Result {i} (similarity: {r['score']}) ---")
        lines.append(f"Source: {r['source']}")
        lines.append(f"Section: {r['title']}")

        # Include metadata when available
        if r.get("entry_title"):
            lines.append(f"Entry: {r['entry_title']}")
        if r.get("type"):
            lines.append(f"Type: {r['type']}")
        if r.get("category"):
            lines.append(f"Category: {r['category']}")
        if r.get("confidence"):
            lines.append(f"Confidence: {r['confidence']}")
        if r.get("related"):
            lines.append(f"Related: {', '.join(r['related'])}")

        lines.append("")
        lines.append(r["content"])
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# 5. CLI entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Vector Knowledge Base Search")
    parser.add_argument("query", help="Search query")
    parser.add_argument("--top", type=int, default=5, help="Number of results (default: 5)")
    parser.add_argument("--type", default=None,
                        help="Filter by content type (framework, technique, strategy, etc.)")
    parser.add_argument("--data", default=None,
                        help="Path to kb_data/ directory (default: auto-detect)")
    args = parser.parse_args()

    provider = get_embedding_provider()

    # Auto-detect kb_data/ relative to this script's location
    if args.data:
        data_dir = args.data
    else:
        script_dir = Path(__file__).resolve().parent
        data_dir = str(script_dir.parent / "kb_data")

    embeddings, chunks = load_embeddings(data_dir)
    results = search(args.query, embeddings, chunks, provider,
                     top_n=args.top, type_filter=args.type)
    print(format_results(results, args.query))


if __name__ == "__main__":
    main()
